config/routes.rb
Rails.application.routes.draw do
  resources :episodes do
    # define custom restful routes
    collection do
      get 'random'
    end
  end

  root to: 'episodes#random'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def random
    episodes = Episode.all
    rng = Random.new
    # episodes[50] # returns the 51st episode
    # rng.rand(100) # returns a random number from 0 to 100
    random_episode_index = rng.rand(episodes.count) + 1
    @random_episode = episodes[random_episode_index]

    respond_to do |format|
      format.html
      format.json { render :json => @random_episode.to_json }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :season, :episode_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_with(model: episode, local: true) do |form| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :episode_name %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.text_field :season, id: :episode_season %>
  </div>

  <div class="field">
    <%= form.label :episode_number %>
    <%= form.text_field :episode_number, id: :episode_episode_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Season</th>
      <th>Episode number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.name %></td>
        <td><%= episode.season %></td>
        <td><%= episode.episode_number %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/random.html.erb
<div class="wrap">

  <div class="jumbotron">
  </div>

    <div class="container-fluid">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">

            <div id="episode-display">
              <h3>The Simpsons Random Episode Generator!</h3>
              <h2>
               Season <%= @random_episode.season %> Episode <%= @random_episode.episode_number %>: <%= @random_episode.name%>
               </h2>

              <center>
                <%= link_to 'Regenerate', random_episodes_path %>
              </center><br>
            </div>

          </div>
        </div>

      <div class="row">
        <div id="donut">
          <%= image_tag "donut1.png" %>
        </div>
      </div>

  </div> <!-- end container-->
</div> <!-- end wrap-->

<div class="modal fade" id="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Info</h4>
      </div>
      <div class="modal-body">
        <p>I really, really like The Simpsons, so I made this web app. Everything else is copywrited by Fox Networks. I am just a fan with a lot of time on my hands!
        <br>My personal site is here: <a href="#">bam!</a>
        <br>Tapped Out screenname: pukahontas
        <br>Screenshot is from the episode "Brother from Another Series"
        <br>Thanks for visiting!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-sm" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
$(function() {
    $('#donut').on('mouseover', function() {
        $('#modal').modal('show');
    });
});
</script>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @episode.name %>
</p>

<p>
  <strong>Season:</strong>
  <%= @episode.season %>
</p>

<p>
  <strong>Episode number:</strong>
  <%= @episode.episode_number %>
</p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpsonsEpisodePicker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>